telegram:
  bot:
    token: token
    admin: 5540407547
spring:
  datasource:
    url: jdbc:postgresql://crossover.proxy.rlwy.net:46893/railway
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
server:
  port: 8085
