telegram:
  bot:
    token: 7163511047:AAFtyJ5r6V6OX3iDsKOnXgHlZRTK5eglaSg
    admin: 5540407547
spring:
  datasource:
    url: jdbc:postgresql://mainline.proxy.rlwy.net:30074/railway
    username: postgres
    password: wANFhnwoRcXXKMJyDrkiSoycYAostcTU
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB

server:
  port: 8443
  ssl:
    enabled: true
    key-store: src/main/resources/keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: said.4587


